- name: get join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  become: yes
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  